/** In-app Workbench feature guides — how-tos for every sitemap row. */

export type GuideLink = { title: string; href: string };

export type WorkbenchGuide = {
  slug: string;
  title: string;
  featureHref: string;
  featureLabel: string;
  summary: string;
  audience: string;
  whenToUse: string;
  steps: string[];
  related: GuideLink[];
  status: "stub" | "draft" | "ready";
};

function r(title: string, href: string): GuideLink {
  return { title, href };
}

export const WORKBENCH_GUIDES: WorkbenchGuide[] = [
  {
    slug: "welcome",
    title: "Operations Center",
    featureHref: "/workbench",
    featureLabel: "Open Operations Center",
    summary: "Home dashboard, rankings, and the Workbench sitemap with a Guide link on every area you can open.",
    audience: "All signed-in staff (nav items still filter by role).",
    whenToUse: "Start here at the beginning of a shift, or whenever you need to find a page or its how-to.",
    steps: [
      "Sign in and land on /workbench. The Operations Center is the home dashboard.",
      "Scan KPI cards and today’s queue. Use the date range if you are comparing periods.",
      "Open a ranking card (audit candidates, used/new system buyers, warm parts, sell-to-Titan) to jump into that customer.",
      "Scroll to Site map. Groups match the top nav: AI, CRM, Marketing, Sales & Pay, Inventory.",
      "Use Open to go to the feature, or Guide to read this how-to style page.",
      "Only pages your tier and capabilities allow appear. Owners see Team; staff see My Pay instead.",
      "Use the bell next to Help for persisted alerts (hot leads, stage suggestions, stalled qualified, goal thresholds).",
      "Use the ? circle to Ask how to use a page, or send Feedback to owners/ops leads.",
      "View site opens the public Titan site in the same browser; Sign out ends the staff session.",
      "If you are lost, open All guides from the sitemap header or /workbench/guides.",
    ],
    related: [r("Actions", "/workbench/guides/actions"), r("Analytics", "/workbench/guides/analytics"), r("All guides", "/workbench/guides")],
    status: "ready",
  },
  {
    slug: "studio",
    title: "AI Studio",
    featureHref: "/workbench/studio",
    featureLabel: "Open AI Studio",
    summary: "Draft email and social copy, generate images, or run Studio Agent against a customer.",
    audience: "Marketing (owners see all capabilities).",
    whenToUse: "You need Titan-voice copy, an image, or an agent to look up a lead, draft outreach, or log an engagement.",
    steps: [
      "Open AI Studio. Pick Text and Image, or Agent, from the mode control.",
      "Optionally load a design preset so the system prompt matches Titan voice.",
      "For text: write or paste the user prompt, attach a segment or customer if the draft is account-specific, then generate.",
      "Edit the output in the textarea. Promote to a template or campaign when the copy is good enough to reuse.",
      "Promote also saves a gold eval case (redacted). Use Save as gold if you signed off without promoting.",
      "For images: switch to Image mode, prompt, then keep or discard the result.",
      "For Agent: pick a customer when you can. Speak or type. Intents include lookup, research, draft_copy, log_engagement, and note.",
      "Review the agent result card, then jump to the customer timeline, Sales, or a campaign as needed.",
      "Mic works in Text and Image as well as Agent; stopping or changing mode ends recording.",
      "If OpenRouter is not configured, Studio will say so — drafts cannot run until the API key is set.",
    ],
    related: [r("Templates", "/workbench/guides/templates"), r("Campaigns", "/workbench/guides/campaigns"), r("Analytics", "/workbench/guides/analytics")],
    status: "ready",
  },
  {
    slug: "actions",
    title: "Actions",
    featureHref: "/workbench/actions",
    featureLabel: "Open Actions",
    summary: "Today’s team queue plus live Analytics progressions (stage suggestions, stalled leads, email signals).",
    audience: "Sales, marketing, or support.",
    whenToUse: "You want a single list of what to work next instead of hunting across Analytics and Customers.",
    steps: [
      "Open Actions from the AI menu.",
      "Pinned today is a planned queue (sample rows until you replace them with live team planning).",
      "Open a pinned row to follow its workspace path (Studio, customer, campaign).",
      "Live items load from Analytics progressions: suggested stage moves, qualified 7d+ stalls, inbound email signals.",
      "Use the primary link on a live item to open the customer, or the listed action (Studio Agent, draft nurture, record sale).",
      "Apply a suggested stage from the customer page or Analytics so the pipeline stays honest.",
      "Log the call or paste the thread in Studio Agent so the next progression is based on real engagement.",
      "Won deals belong on Sales with a lead owner, not only as a stage change.",
      "If live items fail to load, confirm you have sales or marketing access and the API is up.",
      "Return to Operations Center when you need rankings instead of a queue.",
    ],
    related: [r("Analytics", "/workbench/guides/analytics"), r("Studio", "/workbench/guides/studio"), r("Customers", "/workbench/guides/customers")],
    status: "ready",
  },
  {
    slug: "analytics",
    title: "Analytics",
    featureHref: "/workbench/analytics",
    featureLabel: "Open Analytics",
    summary: "Live visitors, lead-stage pipeline, recent engagements, and actionable progressions.",
    audience: "Sales or marketing.",
    whenToUse: "You need to see who is on the site now, where the pipeline sits, and which accounts need a stage move or follow-up.",
    steps: [
      "Open Analytics. Pipeline tiles show counts by stage (new through won/lost).",
      "Click a stage tile to list customers in that stage.",
      "Read progressions: suggested stages, stalled qualified leads, inbound email signals.",
      "Use Move to stage, Open Studio Agent, or Draft nurture from a progression.",
      "Live visitors (and hot leads) refresh on a short interval — click through to the customer or session context.",
      "Recent engagements show channel, outcome, and stage. Open the customer for the full timeline.",
      "The header bell stores the same class of alerts (hot lead, stage suggestion, stalled, goal threshold) per staff.",
      "When a deal actually closes, log it on Sales with closer and lead owner so commissions are correct.",
      "Site Traffic is a separate page for pageviews and sources over a date range.",
      "If visitors look empty, confirm public site tracking is hitting the API (ad blockers can hide events).",
    ],
    related: [r("Traffic", "/workbench/guides/traffic"), r("Actions", "/workbench/guides/actions"), r("Sales", "/workbench/guides/sales")],
    status: "ready",
  },
  {
    slug: "traffic",
    title: "Site traffic",
    featureHref: "/workbench/traffic",
    featureLabel: "Open Site traffic",
    summary: "Pageviews, sessions, top pages, and sources for the public site.",
    audience: "Sales or marketing.",
    whenToUse: "You need range-based traffic (24h to 6 months), not the 15-minute live visitor strip on Analytics.",
    steps: [
      "Open Site traffic from the AI menu.",
      "Pick a range (24 hours, 7 / 30 / 90 days, or 6 months).",
      "Read pageviews, events, and unique sessions for that window.",
      "Scan top pages to see which inventory or content URLs get views.",
      "Scan sources to see how people arrive (direct, referrer labels from events).",
      "Cross-check a busy path against Analytics live visitors if you are on shift now.",
      "Use a high-view product page as context when drafting Studio or campaign copy.",
      "If GraphQL fails, you still have REST Analytics — traffic here uses the staff GraphQL endpoint.",
      "Empty charts usually mean no events in range, not a missing page.",
      "Owners do not need a special role beyond sales/marketing capability.",
    ],
    related: [r("Analytics", "/workbench/guides/analytics"), r("Campaigns", "/workbench/guides/campaigns")],
    status: "ready",
  },
  {
    slug: "insights",
    title: "Market Map",
    featureHref: "/workbench/insights",
    featureLabel: "Open Market Map",
    summary: "Graph of customers, segments, opportunities, and competitors — layout from SQL, not an LLM.",
    audience: "Sales or marketing.",
    whenToUse: "You want relationship context (who sits with which segment or competitor) before a call or campaign.",
    steps: [
      "Open Market Map (Insights).",
      "Choose a scope if the page offers market vs a tighter graph.",
      "Click a customer node to jump to the 360° dossier.",
      "Follow edges to segments, parts tags, or competitor listings.",
      "Use filters when the graph is dense so you are not panning blindly.",
      "Hot or opportunity-tagged nodes are a prompt to open Analytics or Studio Agent, not to auto-send mail.",
      "Competitor nodes only appear after sources exist and a scrape has run (needs Firecrawl on the API).",
      "Do not treat the map as a send list — build a Segment or Goal for outreach.",
      "If the map is empty, import or create customers first.",
      "Return to Customers when you need search and import instead of a graph.",
    ],
    related: [r("Customers", "/workbench/guides/customers"), r("Competitors", "/workbench/guides/competitors"), r("Goals", "/workbench/guides/goals")],
    status: "ready",
  },
  {
    slug: "briefings",
    title: "Briefings",
    featureHref: "/workbench/briefings",
    featureLabel: "Open Briefings",
    summary: "Daily AI staff reports (and optional email/Slack) summarizing activity and priorities.",
    audience: "Marketing (owners included).",
    whenToUse: "Start of day: what moved, who is hot, what to work — without opening every CRM screen.",
    steps: [
      "Open Briefings and read the latest generated report.",
      "Use charts or lists in the briefing to jump to named customers or campaigns when links exist.",
      "Treat counts and trends as the source of truth; do not invent extra names that are not in the report.",
      "Nightly generation needs CRON_SECRET hitting POST /api/v1/workbench/ai/jobs/daily-briefing.",
      "OpenRouter must be enabled for AI narrative; otherwise you will see empty or fallback copy.",
      "Optional Slack/email delivery uses webhook and Resend settings — confirm those in env if staff expect a ping.",
      "Follow a hot lead from the briefing into Analytics, Actions, or Studio Agent.",
      "Log the follow-up as an engagement so tomorrow’s briefing is not repeating stale advice.",
      "Do not send campaigns from the briefing itself — open Campaigns when you are ready to arm a sequence.",
      "If the page is blank after cron, check API logs and that the job authenticated.",
    ],
    related: [r("Analytics", "/workbench/guides/analytics"), r("Studio", "/workbench/guides/studio")],
    status: "ready",
  },
  {
    slug: "customers",
    title: "Customers",
    featureHref: "/workbench/customers",
    featureLabel: "Open Customers",
    summary: "Searchable CRM list, CSV import, and per-account timeline (engagements, campaigns, notes).",
    audience: "Sales, support, or marketing.",
    whenToUse: "You need to find an account, import a list, or see everything that happened on one customer.",
    steps: [
      "Open Customers. Search by email, name, company, or website.",
      "Open a row for the 360° view: stage, consent, timeline, logo if present.",
      "Add or edit contact fields; keep marketing consent honest — campaigns skip no-consent and suppressed.",
      "Use the timeline for engagements, campaign recipient status, and related activity.",
      "Log a call or paste email via Studio Agent with this customer in context.",
      "Import a CRM list from the customer import flow when onboarding (distinct from Parts Import).",
      "Move stage when the relationship actually changed; Analytics suggestions still need a human apply.",
      "When they buy, Log sale on Sales with this customer, closer, and lead owner.",
      "Use Segments or Goals to group accounts for campaigns — do not blast from the full list.",
      "If search misses, check website and company fields; they feed the search document.",
    ],
    related: [r("Segments", "/workbench/guides/segments"), r("Studio", "/workbench/guides/studio"), r("Sales", "/workbench/guides/sales")],
    status: "ready",
  },
  {
    slug: "segments",
    title: "Segments",
    featureHref: "/workbench/segments",
    featureLabel: "Open Segments",
    summary: "Saved audience filters for campaigns, outreach, and goal-linked membership.",
    audience: "Sales, support, or marketing.",
    whenToUse: "You need a reusable list (consenting, by stage, by opportunity type) before you send mail.",
    steps: [
      "Open Segments and review existing audiences.",
      "Create a segment with filters that match how you sell (stage, tags, consent, opportunity).",
      "Preview matching customers before you attach the segment to a campaign.",
      "AI-proposed segments need Approve — do not assume a proposal is live.",
      "Goal-linked segments refresh on the goals job; first link may sit pending until an owner/ops lead approves.",
      "Use the segment when creating a Campaign (sequenced or one-shot).",
      "Use the same segment in Studio as context so drafts match the audience.",
      "Edit filters when membership looks wrong; then preview again.",
      "Do not delete a segment that a live campaign still targets until you retarget.",
      "Outreach can use a small ad-hoc list; prefer segments for anything you will repeat.",
    ],
    related: [r("Goals", "/workbench/guides/goals"), r("Campaigns", "/workbench/guides/campaigns"), r("Customers", "/workbench/guides/customers")],
    status: "ready",
  },
  {
    slug: "goals",
    title: "Goals",
    featureHref: "/workbench/goals",
    featureLabel: "Open Goals",
    summary: "Marketing goals that keep opportunity-based segments fresh (hot leads, parts, used/new systems).",
    audience: "Sales, support, or marketing.",
    whenToUse: "You want membership to follow opportunity snapshots instead of a one-time static filter.",
    steps: [
      "Open Goals and read each goal’s opportunity types and linked segment.",
      "Run or wait for opportunity detect so snapshots exist (manual job or cron).",
      "Create or refresh a goal; set draft-on-threshold if you want a notification when membership is large enough to draft.",
      "Approve the first goal→segment link when it is pending — automation does not invent live segments unsupervised.",
      "Nightly refresh updates membership; check last member count on the goal.",
      "When threshold is crossed, staff with marketing/sales get an in-app notification.",
      "Open the linked segment, then Campaigns or Studio to draft — sending stays human.",
      "Tune opportunity types if the wrong accounts appear (warm parts vs sell-equipment vs hot_lead).",
      "Disable a goal instead of deleting if you may turn it back on.",
      "If counts stay zero, confirm warmth/opportunity jobs have run on this database.",
    ],
    related: [r("Segments", "/workbench/guides/segments"), r("Analytics", "/workbench/guides/analytics"), r("Campaigns", "/workbench/guides/campaigns")],
    status: "ready",
  },
  {
    slug: "templates",
    title: "Templates",
    featureHref: "/workbench/templates",
    featureLabel: "Open Templates",
    summary: "Reusable email HTML/text for campaigns and sequenced steps.",
    audience: "Marketing.",
    whenToUse: "Copy is approved and you will send it more than once, or you need a named step in a sequence.",
    steps: [
      "Open Templates. Create one or promote a Studio draft (promote can save gold).",
      "Set subject, preview line, and HTML/text bodies. Keep claims factual — no invented FDA or lifetime warranty language.",
      "Preview the inbox rendering before you attach the template to a campaign.",
      "Name templates so sequenced campaigns can pick step 1 vs step 2 clearly.",
      "Edit live templates carefully if a campaign already points at them.",
      "Use a segment in Studio when drafting so merge-style context stays account-true.",
      "Do not put suppressed or no-consent assumptions in the copy; the sender still skips those recipients.",
      "Clone a winning template rather than overwriting it if you are testing tone.",
      "Social posts are not templates — use Social or Studio social draft.",
      "When the template is ready, open Campaigns and select it.",
    ],
    related: [r("Studio", "/workbench/guides/studio"), r("Campaigns", "/workbench/guides/campaigns")],
    status: "ready",
  },
  {
    slug: "campaigns",
    title: "Campaigns",
    featureHref: "/workbench/campaigns",
    featureLabel: "Open Campaigns",
    summary: "Resend email campaigns, including sequenced steps, daily quota, arm/pause, and mail-only domains.",
    audience: "Marketing.",
    whenToUse: "You have a segment, a template (or sequence), and you are ready for humans to arm sending — not auto-blast.",
    steps: [
      "Open Campaigns and create a campaign with a name and target segment.",
      "Attach a template, or define sequence steps with delays if this is a drip.",
      "Confirm the from domain is a mail-only sending domain configured in Resend.",
      "Recipients without marketing consent or who are suppressed are skipped — do not fight that.",
      "Arm the campaign when copy and segment are reviewed. Pause if something looks wrong mid-flight.",
      "Daily quota is advanced by POST /api/v1/workbench/ai/jobs/campaigns-tick (cron secret).",
      "Open a campaign to watch recipient status and HTML inbox preview.",
      "Use progress on the list view to see how far a sequence has gotten.",
      "Do not use Campaigns for a single personal follow-up — use Outreach or a logged engagement.",
      "After replies come in, log them via Studio Agent and update stage; won revenue goes on Sales.",
    ],
    related: [r("Templates", "/workbench/guides/templates"), r("Segments", "/workbench/guides/segments"), r("Outreach", "/workbench/guides/outreach")],
    status: "ready",
  },
  {
    slug: "social",
    title: "Social",
    featureHref: "/workbench/social",
    featureLabel: "Open Social",
    summary: "Queue LinkedIn (and similar) posts through Make.com webhooks.",
    audience: "Marketing.",
    whenToUse: "You have approved social copy and Make is wired; you are not posting from a personal LinkedIn login in Workbench.",
    steps: [
      "Draft copy in Studio (social) or write it on Social.",
      "Open Social and create or queue the post.",
      "Confirm the Make webhook URL is set on the API — without it, queueing will not publish.",
      "Keep claims as conservative as email (no fake certifications).",
      "Schedule or send according to the Social UI once Make is connected.",
      "Do not treat Social as email; campaigns still go through Resend.",
      "If a post fails, check Make scenario history, then retry from Social.",
      "Save winning copy as a Studio preset or note so the next post stays on-voice.",
      "Link back to a public parts or contact URL rather than inventing landing pages.",
      "Skip this page until Make is configured — the rest of Workbench does not depend on it.",
    ],
    related: [r("Studio", "/workbench/guides/studio"), r("Campaigns", "/workbench/guides/campaigns")],
    status: "ready",
  },
  {
    slug: "outreach",
    title: "Outreach",
    featureHref: "/workbench/outreach",
    featureLabel: "Open Outreach",
    summary: "One-off email to a small set of recipients outside a full campaign sequence.",
    audience: "Marketing.",
    whenToUse: "A short list needs a personal blast now, and you do not want to arm a sequenced campaign.",
    steps: [
      "Open Outreach and use the composer.",
      "Choose recipients or a small list. Prefer people who have marketing consent.",
      "Paste or write copy; you can start from a Studio draft.",
      "Preview before send. Sending still requires Resend to be configured.",
      "Send. This is not a multi-step sequence — use Campaigns for drips.",
      "Log the thread or outcome in Studio Agent on each important account.",
      "If someone replies with buying intent, update stage and consider Sales when they close.",
      "Do not use Outreach to bypass campaign skip rules for suppressed addresses.",
      "For repeating audiences, save a Segment and switch to Campaigns next time.",
      "Check Resend logs if mail does not arrive.",
    ],
    related: [r("Campaigns", "/workbench/guides/campaigns"), r("Studio", "/workbench/guides/studio"), r("Customers", "/workbench/guides/customers")],
    status: "ready",
  },
  {
    slug: "sales",
    title: "Sales",
    featureHref: "/workbench/sales",
    featureLabel: "Open Sales",
    summary: "Log won conversions with closer and lead owner, and review KPIs for the selected date range.",
    audience: "Sales capability. Attribution charts are owner-only.",
    whenToUse: "A deal closed, or you need won revenue, win rate, source mix, or (if owner) who got credit.",
    steps: [
      "Open Sales. Pick Last 7 / 30 / 90 days for KPIs and the conversions table.",
      "Read won revenue, deal count, average deal, win rate, and median days to close (customer created → close).",
      "Win rate is won vs lost in range when lost rows exist; otherwise it is labeled won vs open pipeline.",
      "Weekly won revenue and source mix (engagement / campaign / unattributed) are for all sales staff.",
      "Owners also see attribution: dollars where closer ≠ lead owner, pipeline-to-cash stages, won $ by closer and by lead owner.",
      "To log a sale: select customer, amount, closer (owner/partner OK; default is you), and required lead owner.",
      "Lead owner is suggested from engagement staff or campaign creator email mapped to staff.",
      "Optionally attach engagement or campaign as source so mix charts stay honest.",
      "Submit Log sale. Won rows post to the earnings ledger using the staff pay package (lead_owner vs closer vs split).",
      "Staff accept packages under My Pay before they should expect those earnings to show.",
    ],
    related: [r("Team", "/workbench/guides/team"), r("My Pay", "/workbench/guides/mypay"), r("Customers", "/workbench/guides/customers")],
    status: "ready",
  },
  {
    slug: "service",
    title: "Service",
    featureHref: "/workbench/service",
    featureLabel: "Open Service",
    summary: "Field repair, site jobs, and PET/CT audits that can flow into payroll.",
    audience: "Technician or support.",
    whenToUse: "You are scheduling or completing on-site work, including audits that may include a report.",
    steps: [
      "Open Service and review open jobs.",
      "Create a job: customer, type (repair vs audit), and notes.",
      "Assign the technician who will be on site.",
      "Complete the job with hours and/or a flat amount as the form requires.",
      "Attach an audit report when the job type expects one.",
      "Completed jobs can create earnings per the staff pay package (service line).",
      "Void only if the owner/ops process allows — voiding hits the ledger.",
      "If the visit produced a sales lead, log an engagement and consider a Sales conversion separately.",
      "Keep customer stage in CRM in sync when the site visit changes the relationship.",
      "Accounting reviews service dollars on Payroll; technicians check My Pay.",
    ],
    related: [r("Customers", "/workbench/guides/customers"), r("Payroll", "/workbench/guides/payroll"), r("My Pay", "/workbench/guides/mypay")],
    status: "ready",
  },
  {
    slug: "team",
    title: "Team",
    featureHref: "/workbench/team",
    featureLabel: "Open Team",
    summary: "Owner-only roster, tiers, capabilities, and visible pay packages.",
    audience: "Owner tier only.",
    whenToUse: "You are adding staff, changing roles, or creating/editing commission and hourly packages.",
    steps: [
      "Open Team. Only owners can use this page.",
      "Add staff by email, tier (Owner / Ops lead / Staff), and capabilities if Staff.",
      "Ops lead gets marketing, sales, support, and technician — not accounting or Team.",
      "Scroll to Pay packages. Read existing name, commission %, who it credits, hourly rate, and terms.",
      "Create a package or Edit one. Default new packages credit lead_owner (marketing still paid when an owner closes).",
      "Assign a package to staff with the picker (not only a hidden default). They must accept under My Pay.",
      "A warning appears if marketing staff are on a closer-only package.",
      "Do not silently rewrite historical packages; clone or edit deliberately.",
      "Edit roles when someone changes function — nav and APIs follow capabilities.",
      "Use Payroll (accounting) for payouts, not Team.",
    ],
    related: [r("My Pay", "/workbench/guides/mypay"), r("Payroll", "/workbench/guides/payroll"), r("Sales", "/workbench/guides/sales")],
    status: "ready",
  },
  {
    slug: "feedback",
    title: "Staff feedback",
    featureHref: "/workbench/feedback",
    featureLabel: "Open Staff feedback",
    summary: "Inbox of messages staff send from the Help flyout Feedback tab.",
    audience: "Owner or ops lead.",
    whenToUse: "You are triaging what is broken, missing, or confusing on a Workbench page.",
    steps: [
      "Staff open Help (?), Feedback tab, describe the issue, and send. The page path is attached.",
      "Owners and ops leads open Staff feedback from Sales & Pay.",
      "Read unread rows first. Note which page_path they came from.",
      "Mark a row read when you have seen it.",
      "Fix the product or reply out of band — this inbox is not a chat thread.",
      "Ask tab in Help answers from the guide catalog; it is not the same as Feedback.",
      "If staff cannot send, they are not signed in or the API rejected the post.",
      "Do not expect marketing staff to see this inbox.",
      "Repeat issues on the same path are a signal to improve that feature’s guide.",
      "Operations Center still has Ask/Feedback for everyone; only this page lists the queue.",
    ],
    related: [r("Operations Center", "/workbench/guides/welcome"), r("All guides", "/workbench/guides")],
    status: "ready",
  },
  {
    slug: "mypay",
    title: "My Pay",
    featureHref: "/workbench/mypay",
    featureLabel: "Open My Pay",
    summary: "Staff view to read and accept a pending pay package so sales, hours, and jobs can earn.",
    audience: "Non-owner staff (hidden for owners).",
    whenToUse: "An owner assigned you a package, or you want to see current commission and hourly terms.",
    steps: [
      "Open My Pay from Sales & Pay (owners do not see this nav item).",
      "Read the pending package name, commission rate, whether it credits closer, lead owner, or both, and hourly rate.",
      "Read terms_markdown in full before accepting.",
      "Accept the assignment. Earnings from that point follow the package.",
      "Won sales credit you when you are the person the package pays (often lead owner).",
      "Submit time entries as your workflow requires so hourly can accrue after acceptance.",
      "Completed service jobs may add a service line.",
      "If nothing is pending, ask an owner to assign a package on Team.",
      "Questions about a paid/owed ledger belong with accounting on Payroll, not this accept screen.",
      "Do not log sales here — use Sales.",
    ],
    related: [r("Sales", "/workbench/guides/sales"), r("Service", "/workbench/guides/service")],
    status: "ready",
  },
  {
    slug: "payroll",
    title: "Payroll",
    featureHref: "/workbench/payroll",
    featureLabel: "Open Payroll",
    summary: "Owner/accounting payout dashboard: ledger, owed vs paid, and mix of commission, hourly, service, adhoc.",
    audience: "Accounting capability or owner.",
    whenToUse: "You are reviewing what the company owes staff or recording an adhoc amount.",
    steps: [
      "Open Payroll. Set from/to dates like other money screens.",
      "Read per-staff commission, hourly, service, adhoc, owed, and paid.",
      "Use the charts for owed-by-person and mix; they use the same Workbench tooltip styling as Sales.",
      "Open ledger rows to see source (conversion, time, job, adhoc).",
      "Mark paid when money has actually gone out.",
      "Record adhoc only with a note — it is not a substitute for logging a sale.",
      "Void paths exist for conversions and jobs when an owner must reverse; use sparingly.",
      "Sales attribution (who generated the lead) is on Sales for owners; Payroll is dollars owed.",
      "Staff will not see this page without accounting — they use My Pay.",
      "If owed looks wrong, check Team package (lead_owner vs closer) and whether the staff accepted.",
    ],
    related: [r("Team", "/workbench/guides/team"), r("Sales", "/workbench/guides/sales")],
    status: "ready",
  },
  {
    slug: "parts",
    title: "Parts",
    featureHref: "/workbench/parts",
    featureLabel: "Open Parts",
    summary: "Inventory catalog: part numbers, stock, pricing, categories.",
    audience: "Sales, support, or technician.",
    whenToUse: "You are updating a SKU, checking qty, or preparing a quote from live inventory.",
    steps: [
      "Open Parts. Search by part number or description.",
      "Open a part to edit price, quantity, and category.",
      "Keep qty honest — public site and alerts depend on it.",
      "Assign a category so the public catalog and filters stay consistent.",
      "Use Import for bulk CSV updates instead of hand-editing dozens of rows.",
      "Back-in-stock Alerts fire from subscribers when qty returns — coordinate with Alerts.",
      "Competitor scrape is a compare tool, not a price overwrite.",
      "Do not invent GE/FDA claims in part copy; keep descriptions factual.",
      "Link a warm customer to a part from CRM/Studio when they asked about that SKU.",
      "After edits, spot-check the public part page.",
    ],
    related: [r("Categories", "/workbench/guides/categories"), r("Import", "/workbench/guides/import"), r("Alerts", "/workbench/guides/alerts")],
    status: "ready",
  },
  {
    slug: "categories",
    title: "Categories",
    featureHref: "/workbench/categories",
    featureLabel: "Open Categories",
    summary: "Taxonomy for parts (name and slug) used by the public catalog and admin filters.",
    audience: "Sales, support, or technician.",
    whenToUse: "You need a new family of parts or a rename that should show on the public site.",
    steps: [
      "Open Categories and list existing names/slugs.",
      "Add a category with a stable slug; changing slugs later can break public URLs.",
      "Rename only when you intend the public nav to change.",
      "Assign parts to the category from Parts.",
      "Do not duplicate near-identical categories — merge conceptually first.",
      "Import can set category columns; confirm mapping after upload.",
      "Check the public catalog filters after a new category has parts.",
      "Delete/archive only when no parts still need that bucket.",
      "Competitors are not categories — they live under Competitors.",
      "Tell marketing if a new category should get a campaign or landing mention.",
    ],
    related: [r("Parts", "/workbench/guides/parts"), r("Import", "/workbench/guides/import")],
    status: "ready",
  },
  {
    slug: "competitors",
    title: "Competitors",
    featureHref: "/workbench/competitors",
    featureLabel: "Open Competitors",
    summary: "Competitor sources and scraped listings for price compare (Firecrawl).",
    audience: "Sales or marketing.",
    whenToUse: "You are tracking another dealer’s public listings against Titan inventory.",
    steps: [
      "Open Competitors and add a source URL you are allowed to scrape.",
      "Run scrape from the UI or wait for POST /api/v1/workbench/ai/jobs/competitors-scrape (cron).",
      "FIRECRAWL_API_KEY must be set or scrapes will not populate listings.",
      "Compare listings to your Parts prices — do not auto-reprice from scrape.",
      "Use Market Map to see competitor nodes once listings exist.",
      "Keep sources limited; noisy scrapes waste quota and clutter the graph.",
      "Re-run after a competitor redesign if selectors break (job logs will show failures).",
      "Do not paste scraped PII into campaigns.",
      "If the page is empty, this is usually missing Firecrawl, not a Workbench bug.",
      "Sales conversations still get logged on the customer, not on the competitor row.",
    ],
    related: [r("Parts", "/workbench/guides/parts"), r("Market Map", "/workbench/guides/insights")],
    status: "ready",
  },
  {
    slug: "import",
    title: "Import",
    featureHref: "/workbench/import",
    featureLabel: "Open Import",
    summary: "Bulk parts CSV upload into inventory.",
    audience: "Sales, support, or technician.",
    whenToUse: "You have a spreadsheet of SKUs to add or update, not a one-off part edit.",
    steps: [
      "Open Import (this is parts catalog, not the CRM customer import).",
      "Follow the CSV template columns (part number, qty, price, category as documented on the page).",
      "Export or copy from your supplier file into that shape.",
      "Upload and wait for row results. Fix errors and re-upload as needed.",
      "Verify a sample of parts on Parts after success.",
      "Confirm categories exist or were created as you intended.",
      "Qty changes can affect Alerts — warn the person who handles restock mail.",
      "Do not import customer emails here.",
      "Keep a local copy of the CSV you uploaded for audit.",
      "Large files: split if the UI or API times out, then verify counts.",
    ],
    related: [r("Parts", "/workbench/guides/parts"), r("Categories", "/workbench/guides/categories")],
    status: "ready",
  },
  {
    slug: "alerts",
    title: "Alerts",
    featureHref: "/workbench/alerts",
    featureLabel: "Open Alerts",
    summary: "Public back-in-stock subscribers waiting on parts that were unavailable.",
    audience: "Sales, support, or technician.",
    whenToUse: "Stock is returning and you need to know who asked to be notified.",
    steps: [
      "Open Alerts and review subscriber emails per part.",
      "When qty is updated on Parts, use this list to coordinate restock messaging.",
      "Do not dump the list into a marketing campaign unless they also have marketing consent.",
      "Treat this as transactional interest in a SKU, not a nurture segment.",
      "After you notify, keep the list in sync with however the product marks fulfilled (if the UI offers it).",
      "If the list is empty, the public waitlist form may not be wired or nobody subscribed.",
      "Cross-check part numbers against Parts so you are not emailing for the wrong SKU.",
      "Support can mention subscribers when a customer calls about that part.",
      "Owners can still see this with inventory capabilities.",
      "Campaigns for consenting lists stay on Segments + Campaigns, not here.",
    ],
    related: [r("Parts", "/workbench/guides/parts"), r("Customers", "/workbench/guides/customers")],
    status: "ready",
  },
];

export const FEATURE_HREF_TO_GUIDE_SLUG: Record<string, string> = Object.fromEntries(
  WORKBENCH_GUIDES.map((g) => [g.featureHref, g.slug]),
);

export function getGuide(slug: string): WorkbenchGuide | undefined {
  return WORKBENCH_GUIDES.find((g) => g.slug === slug);
}
